# Generated by Django 3.2.4 on 2021-07-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_post_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texts',
            field=models.CharField(default='', max_length=3000, verbose_name='Enter text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='User.user'),
        ),
    ]
