# Generated by Django 3.2.4 on 2021-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
